# Generated by Django 4.1.3 on 2022-11-15 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(related_name='Song_Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
